### ISSUE TITLE
"self.write_byte_data" -> "self.bus.write_byte_data" in sBoard.readInput

### ISSUE THREAD

**Issue by jproney** [Roboteurs/slushengine#6]
Currently, calling the `readInput` method of the `sBoard` class causes the following error:

`'sBoard' object has no attribute 'write_byte_data'`

From the source, it appears that line 109 of `Board.py` should be changed from `  self.write_byte_data(0x17, inputNumber + 8, 0x00)` to `self.bus.write_byte_data(0x17, inputNumber + 8, 0x00)`. Line 110 should also be changed from `result = self.read_byte_data(0x17, inputNumber + 20)
` to `result = self.bus.read_byte_data(0x17, inputNumber + 20)`.

**Comment by Mango-kid** [comment]
fixed. the IO communication will be going through some rework. We are adding some more boards and we want the same functions to cover all of them.
